name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 730335492406.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t my-nginx-image .

      - name: Tag Docker image
        run: docker tag my-nginx-image:latest 730335492406.dkr.ecr.ap-south-1.amazonaws.com/pipeline:latest

      - name: Push Docker image to ECR
        run: docker push 730335492406.dkr.ecr.ap-south-1.amazonaws.com/pipeline:latest
